package publishers;

import baseEntities.IEntity;
import events.IEvent;
import publishers.strategies.IStrategy;

public interface IPublisher extends IEntity<Integer> {

	/**
	 * Method to publish a default event via the {@link IStrategy} that is also
	 * generated by this strategy, in the case that an event was not specified
	 */
	void publish();

	/**
	 * Method to publish event specified as per the parameter via the
	 * {@link IStrategy} in the case that an event was specified
	 *
	 * @param event event specified to be published
	 */
	void publish(IEvent event);

}