package publishers;

import baseEntities.IEntity;
import events.IEvent;

public interface IPublisher extends IEntity<Integer> {

	/**
	 * Method to publish a default event via the {@link #publishingStrategy} that is
	 * also generated by this strategy, in the case that an event was not specified
	 */
	void publish();

	/**
	 * Method to publish event specified as per the parameter via the
	 * {@link #publishingStrategy} in the case that an event was specified
	 *
	 * @param event event specified to be published
	 */
	void publish(IEvent event);

}