package events;

import publishers.AbstractPublisher;

/**
 * @author kkontog, ktsiouni, mgrigori
 *
 */
public class EventFactory {

	/**
	 * This is an implementation of the Factory Method design pattern Creates an
	 * instance of any of the subclasses derived from the top level class
	 * AbstractEvent
	 * 
	 * @param eventType        a member of the {@link EventType} enumeration
	 * @param eventPublisherId a number generated by invoking the
	 *                         {@link AbstractPublisher#hashCode()} on the
	 *                         {@link AbstractPublisher} instance issuing the event
	 * @param payload          an object of type {@link EventMessage}
	 * @return
	 */
	public static AbstractEvent createEvent(EventType eventType, AbstractPublisher eventPublisher, EventMessage payload) {
		switch (eventType) {
		case ALPHA_EVENT:
			return new AlphaEvent(EventIDMaker.getNewEventID(), eventPublisher, payload);
		case BETA_EVENT:
			return new BetaEvent(EventIDMaker.getNewEventID(), eventPublisher, payload);
		case GAMMA_EVENT:
			return new GammaEvent(EventIDMaker.getNewEventID(), eventPublisher, payload);
		default:
			return new DefaultEvent(EventIDMaker.getNewEventID(), eventPublisher, payload);
		}
	}

}
